FROM dmonk/aarch64-centos8:latest

RUN [ "cross-build-start" ]

RUN install_packages epel-release
RUN install_packages git gcc-c++ wget make rpm-build git-core gcc-c++ pugixml-devel python2-devel python3-devel
RUN dnf --enablerepo=PowerTools install -y boost-* && dnf clean all



RUN [ "cross-build-end" ]
