stages:
    - build-centos-boost
    - build-centos-uhal
    - build-centos-emp


build-armv7hf-centos7-boost:
    stage: build-centos-boost
    tags:
        - docker-image-build
    variables:
        CONTEXT_DIR: "armv7hf-centos7-boost/"
        TO: ${CI_REGISTRY_IMAGE}/armv7hf-centos7-boost
    script: "echo" # unused but this line is required by GitLab CI

build-armv7hf-centos7-uhal:
    stage: build-centos-uhal
    tags:
        - docker-image-build
    variables:
        CONTEXT_DIR: "armv7hf-centos7-uhal/"
        TO: ${CI_REGISTRY_IMAGE}/armv7hf-centos7-uhal
    script: "echo" # unused but this line is required by GitLab CI

build-armv7hf-centos7-emp:
    stage: build-centos-emp
    tags:
        - docker-image-build
    variables:
        CONTEXT_DIR: "armv7hf-centos7-emp/"
        BUILD_ARG_1: "GITLAB_USERNAME=$USERNAME"
        BUILD_ARG_2: "GITLAB_PASSWORD=$PASSWORD"
        TO: ${CI_REGISTRY_IMAGE}/armv7hf-centos7-emp
    script: "echo" # unused but this line is required by GitLab CI


build-aarch64-centos8-boost:
    stage: build-centos-boost
    tags:
        - docker-image-build
    variables:
        CONTEXT_DIR: "aarch64-centos8-boost/"
        TO: ${CI_REGISTRY_IMAGE}/aarch64-centos8-boost
    script: "echo" # unused but this line is required by GitLab CI

build-aarch64-centos8-uhal:
    stage: build-centos-uhal
    tags:
        - docker-image-build
    variables:
        CONTEXT_DIR: "aarch64-centos8-uhal/"
        TO: ${CI_REGISTRY_IMAGE}/aarch64-centos8-uhal
    script: "echo" # unused but this line is required by GitLab CI
