FROM dmonk/armv7hf-alpine-boost:latest

RUN [ "cross-build-start" ]

WORKDIR "/"
RUN git clone --depth=1 -b v2.7.0  https://github.com/ipbus/ipbus-software.git
WORKDIR "/ipbus-software"
RUN make Set=uhal -j 16

RUN make Set=uhal install

RUN [ "cross-build-end" ]
