FROM gitlab-registry.cern.ch/dmonk/docker-images/armv7hf-centos-uhal:latest

ARG GITLAB_USERNAME
ARG GITLAB_PASSWORD

COPY build-utils /opt/cactus/build-utils

RUN [ "cross-build-start" ]

WORKDIR "/"
RUN git clone https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@gitlab.cern.ch/p2-xware/software/emp-toolbox.git

WORKDIR "/emp-toolbox"
RUN make -j 8

RUN [ "cross-build-end" ]
