FROM httpd:alpine

COPY passwd /passwd
COPY ssh_config /root/.ssh/config

RUN apk update && apk upgrade
RUN apk add py3-setuptools apache2-mod-wsgi git sshpass openssh-client
RUN pip3 install --upgrade pip
RUN pip3 install flask

WORKDIR "/"
COPY passwd /passwd
RUN  cat /dev/zero | ssh-keygen -q -N ""
RUN sshpass -f /passwd ssh-copy-id -p 222 cmx@pcuptracker001
RUN git clone https://gitlab.cern.ch/dmonk/wempbutler.git
WORKDIR "/wempbutler"
RUN chmod +x deploy.sh

ENTRYPOINT ["/wempbutler/deploy.sh"]
