FROM balenalib/armv7hf-alpine:latest

RUN [ "cross-build-start" ]

RUN install_packages git
RUN install_packages g++
RUN install_packages gcc
RUN install_packages wget
RUN install_packages make
RUN install_packages erlang
RUN install_packages boost-dev
RUN install_packages pugixml-dev
RUN install_packages python-dev

RUN mkdir dl
WORKDIR "/dl"
RUN wget -q https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2 && \
	tar --bzip2 -xf boost_1_72_0.tar.bz2
WORKDIR "/dl/boost_1_72_0"
RUN ./bootstrap.sh --prefix=/usr && ./b2 install -j 16

WORKDIR "/"

RUN rm -rf /dl

RUN [ "cross-build-end" ]
