FROM balenalib/armv7hf-alpine:latest

RUN [ "cross-build-start" ]

RUN install_packages git
RUN install_packages g++
RUN install_packages gcc
RUN install_packages wget
RUN install_packages make
RUN install_packages erlang
RUN install_packages boost-dev
RUN install_packages pugixml-dev
RUN install_packages python-dev

RUN [ "cross-build-end" ]
